name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Frontend Build
        run: |
          cd frontend
          npm run build
